### ISSUE TITLE
Better Configuration

### ISSUE THREAD

**Issue by electricjones** [ravenfire/magpie#15]
**NOTE**: This may be the best first issue. Others depend on it.

## Tasks
- [ ] Create a `Config` class with appropriate getters/setters
- [ ] Decide on config options and defaults
- [ ] Allow `Config::fromJson($json)` and `Config::fromJsonFile($path)`
- [ ] Look for a `magpie.json` file and use it as config if it exists
- [ ] Command line option to force a different path for the json config file
- [ ] Allow setting config options at runtime, getting with default, and fallbacks

## Possible configuration options
- Location of the sqlite database
- Allow other types of sql databases (use Illuminate's config)
- Logging setup
- Schedule of Runs
- Password for install and uninstall data
